/* texts.js — корпус интерпретаций продукта, PL и EN.
   Схема композиционная: вместо 700 готовых фраз на транзиты держим фрагменты,
   которые собираются в предложение.

     tPlanet[p].subj + tone[t].verb + nPoint[n] + tPlanet[p].theme + advice

   Так 11 транзитных планет × 13 натальных точек × 3 тона покрываются
   11 + 13 + 3 фрагментами вместо 429.
*/
(function (g) {
  'use strict';

  var PL = {
    ui: {
      brand: 'AstroMap',
      nav: { today: 'Dziś', horoscope: 'Horoskop', chart: 'Karta',
             match: 'Zgodność', numbers: 'Numerologia', moon: 'Księżyc',
             retro: 'Retrogradacje', profile: 'Profil' },
      todayTitle: 'Dziś', horoscopeTitle: 'Horoskop', chartTitle: 'Twoja karta',
      matchTitle: 'Zgodność', numbersTitle: 'Numerologia',
      moonTitle: 'Kalendarz Księżyca', retroTitle: 'Retrogradacje',
      profileTitle: 'Profil',
      needTitle: 'Najpierw dane urodzenia',
      needText: 'Ten ekran liczy się z Twojej daty, godziny i miejsca urodzenia. Uzupełnij je raz — wszystkie pozostałe ekrany policzą się same.',
      needBtn: 'Przejdź do profilu',
      needTextNum: 'Numerologia liczy się z daty urodzenia i imienia. Uzupełnij profil, żeby zobaczyć swoje liczby.',
      needTextMatch: 'Zgodność wymaga dwóch kart. Najpierw uzupełnij swoje dane w profilu, potem dodasz drugą osobę tutaj.',
      skyNow: 'Niebo teraz',
      skyNote: 'Aktualne pozycje planet. Ta karta nie zależy od Twoich danych — liczy się dla całego świata jednakowo.',
      whatYouGet: 'Co policzymy',
      numbersRef: 'Znaczenia liczb',
      matchIntro: 'Jak czytać zgodność',
      matchIntroText: 'Wskaźnik powstaje z aspektów między dwiema kartami: kontakty Słońca, Księżyca, Wenus i Marsa liczą się najmocniej. Composite to trzecia karta, zbudowana z punktów środkowych — pokazuje relację jako osobny byt.',
      profileIntro: 'Godzina urodzenia zmienia Ascendent i domy. Jeśli jej nie znasz, zostaw pole puste — policzymy resztę.',
      getList: [
        'Wskaźniki dnia i aktywne tranzyty',
        'Dokładne daty tranzytów na dzień, tydzień i miesiąc',
        'Karta: planety, aspekty, bilans żywiołów',
        'Zgodność z drugą osobą i karta composite',
        'Numerologia: liczby i cykle osobiste',
        'Kalendarz Księżyca i retrogradacje'
      ],
      indices: 'Wskaźniki dnia',
      indicesNote: 'Liczone z tonu aktywnych tranzytów do odpowiednich punktów Twojej karty. To indeks, nie prognoza.',
      mood: 'Nastrój', work: 'Praca', love: 'Miłość',
      activeTransits: 'Aktywne tranzyty',
      exactDates: 'Dokładne daty',
      noTransits: 'Brak aspektów w orbisie na tę datę.',
      period: { today: 'Dziś', tomorrow: 'Jutro', week: 'Tydzień', month: 'Miesiąc',
                halfyear: 'Pół roku', year: 'Rok' },
      hzGeneral: 'Ogólnie', hzLove: 'Miłość', hzCareer: 'Kariera', hzLuck: 'Szczęście',
      hzQuiet: 'Spokojny okres — brak silnych aspektów w tym obszarze.',
      day: 'Dzień', week: 'Tydzień', month: 'Miesiąc', dateCol: 'Data',
      transitCol: 'Tranzyt', weight: 'Waga pary',
      positions: 'Pozycje', aspects: 'Aspekty', balance: 'Bilans',
      elements: 'Żywioły', modes: 'Krzyże',
      houses: 'Domy (system znakowy)',
      point: 'Punkt', sign: 'Znak', deg: 'Stopień', house: 'Dom',
      motion: 'Ruch', retroCol: 'R', orb: 'Orbis', tone: 'Ton',
      partnerTitle: 'Druga osoba', partnerAdd: 'Policz zgodność',
      partnerName: 'Imię', date: 'Data urodzenia', time: 'Godzina',
      city: 'Miejsce', noTime: 'Nie znam godziny',
      index: 'Wskaźnik zgodności',
      indexNote: 'Skala 38–96, liczona z dwunastu najsilniejszych kontaktów między kartami. Metoda astrologiczna, nie prognoza.',
      strongest: 'Najsilniejsze kontakty',
      composite: 'Composite — karta wspólna',
      compositeNote: 'Karta punktów środkowych: pokazuje relację jako osobny byt, nie sumę dwóch osób.',
      lifePath: 'Droga życia', expression: 'Liczba wyrazu',
      soul: 'Liczba duszy', personalityN: 'Liczba osobowości',
      birthdayN: 'Liczba urodzenia', maturity: 'Liczba dojrzałości',
      pYear: 'Rok osobisty', pMonth: 'Miesiąc osobisty', pDay: 'Dzień osobisty',
      karmic: 'Dług karmiczny', master: 'Liczba mistrzowska',
      nameNeeded: 'Podaj imię w profilu, żeby policzyć liczby z imienia.',
      phase: 'Faza', illum: 'Oświetlenie', moonSign: 'Księżyc w znaku',
      nextFull: 'Najbliższa pełnia', nextNew: 'Najbliższy nów',
      stationing: 'Zmiana kierunku', direct: 'ruch prosty',
      retrograde: 'retrogradacja', noRetro: 'Żadna planeta nie jest teraz retrogradna.',
      save: 'Zapisz', edit: 'Zmień', calc: 'Policz',
      disclaimer: 'Treść ma charakter rozrywkowy i nie zastępuje porady specjalisty.',
      noProfile: 'Uzupełnij dane urodzenia, żeby policzyć kartę.',
      timeMissing: 'Bez godziny urodzenia nie liczymy Ascendentu, MC i domów.'
    },

    signs: ['Baran', 'Byk', 'Bliźnięta', 'Rak', 'Lew', 'Panna',
            'Waga', 'Skorpion', 'Strzelec', 'Koziorożec', 'Wodnik', 'Ryby'],
    elements: { fire: 'Ogień', earth: 'Ziemia', air: 'Powietrze', water: 'Woda' },
    modes: { cardinal: 'Kardynalny', fixed: 'Stały', mutable: 'Zmienny' },
    planets: {
      Sun: 'Słońce', Moon: 'Księżyc', Mercury: 'Merkury', Venus: 'Wenus',
      Mars: 'Mars', Jupiter: 'Jowisz', Saturn: 'Saturn', Uranus: 'Uran',
      Neptune: 'Neptun', Pluto: 'Pluton', Node: 'Węzeł Księżycowy',
      ASC: 'Ascendent', MC: 'MC'
    },
    aspects: {
      conjunction: 'koniunkcja', sextile: 'seksytl', square: 'kwadratura',
      trine: 'trygon', opposition: 'opozycja'
    },

    /* --- фрагменты для транзитов ---------------------------------------- */
    tone: { soft: 'wspiera', hard: 'napina', neutral: 'wzmacnia' },
    toneWord: { soft: 'łagodny', hard: 'trudny', neutral: 'neutralny' },

    tPlanet: {
      Sun: { subj: 'Tranzytujące Słońce', theme: 'widoczność i to, na co idzie Twoja uwaga',
             advice: 'Efekt trwa dzień lub dwa — nie planuj na nim niczego długiego.' },
      Moon: { subj: 'Tranzytujący Księżyc', theme: 'nastrój i potrzeba bliskości',
              advice: 'Trwa kilka godzin. Jeśli reakcja jest mocniejsza niż sprawa, to właśnie ten tranzyt.' },
      Mercury: { subj: 'Tranzytujący Merkury', theme: 'rozmowy, dokumenty i tempo myślenia',
                 advice: 'Dobry moment na wysłanie tego, co leży od tygodnia.' },
      Venus: { subj: 'Tranzytująca Wenus', theme: 'relacje, pieniądze i poczucie wartości',
               advice: 'Krótkie okno, w którym łatwiej o pojednanie i o prośbę o podwyżkę.' },
      Mars: { subj: 'Tranzytujący Mars', theme: 'energia, złość i gotowość do działania',
              advice: 'Skieruj to w ruch lub w pracę, bo inaczej pójdzie w kłótnię.' },
      Jupiter: { subj: 'Tranzytujący Jowisz', theme: 'rozszerzanie i szansa, która wymaga tylko decyzji',
                 advice: 'Trwa kilka tygodni. Główne ryzyko to przeszacowanie sił.' },
      Saturn: { subj: 'Tranzytujący Saturn', theme: 'struktura, granice i cena czasu',
                advice: 'Trwa miesiące. To nie kara, tylko rachunek — zapłać go w małych ratach.' },
      Uranus: { subj: 'Tranzytujący Uran', theme: 'zmiana, której nie planowałeś',
                advice: 'Nie da się przeczekać. Da się wybrać, którą część zmienisz sam.' },
      Neptune: { subj: 'Tranzytujący Neptun', theme: 'rozmycie granic i idealizowanie',
                 advice: 'Zły okres na decyzje wymagające ostrego widzenia. Dobry na twórczość i sen.' },
      Pluto: { subj: 'Tranzytujący Pluton', theme: 'to, co i tak się kończy',
               advice: 'Działa latami. Opór kosztuje więcej niż sama zmiana.' },
      Node: { subj: 'Tranzytujący Węzeł Księżycowy', theme: 'kierunek, w którym ciągnie mimo wygody',
              advice: 'Punkt zwrotny bywa widoczny dopiero po pół roku.' }
    },

    nPoint: {
      Sun: 'Twoje poczucie siebie',
      Moon: 'Twoją potrzebę bezpieczeństwa',
      Mercury: 'Twój sposób mówienia i myślenia',
      Venus: 'Twoje relacje i to, co uznajesz za wartościowe',
      Mars: 'Twoją zdolność do działania i konfrontacji',
      Jupiter: 'Twoje poczucie sensu i skali',
      Saturn: 'Twoje granice i obowiązki',
      Uranus: 'Twoją potrzebę wolności',
      Neptune: 'Twoją wrażliwość i wyobraźnię',
      Pluto: 'Twoją relację z władzą i kontrolą',
      Node: 'Twój kierunek rozwoju',
      ASC: 'Twój sposób wchodzenia w sytuacje',
      MC: 'Twoją pozycję zawodową i to, jak Cię widzą'
    },

    /* --- планета в стихии: для карты ------------------------------------- */
    planetElement: {
      Sun: { fire: 'Twoja tożsamość działa przez ruch i inicjatywę.',
             earth: 'Twoja tożsamość buduje się przez wynik, nie przez ogłoszenie.',
             air: 'Twoja tożsamość istnieje w kontakcie z ludźmi i pomysłami.',
             water: 'Twoja tożsamość opiera się na tym, co czujesz, nie co robisz.' },
      Moon: { fire: 'Emocje masz szybkie i widoczne: wybuch i po wszystkim.',
              earth: 'Uspokaja Cię konkret: rytm, jedzenie, znane miejsce.',
              air: 'Potrzebujesz nazwać uczucie słowami, żeby je przeżyć.',
              water: 'Czujesz więcej, niż mówisz, i dłużej, niż wypada.' },
      Mercury: { fire: 'Mówisz szybciej, niż sprawdzasz. Zaleta na starcie, ryzyko w szczegółach.',
                 earth: 'Myślisz konkretnie i nie znosisz abstrakcji bez przykładu.',
                 air: 'Ciekawość jest Twoim głównym paliwem intelektualnym.',
                 water: 'Rozumiesz przez skojarzenie i nastrój, nie przez tabelę.' },
      Venus: { fire: 'W miłości potrzebujesz tempa i bycia wybranym wprost.',
               earth: 'W miłości liczysz powtarzalność, nie deklaracje.',
               air: 'W miłości rozmowa jest ważniejsza od gestu.',
               water: 'W miłości scalasz się z drugą osobą szybciej, niż to bezpieczne.' },
      Mars: { fire: 'Działasz od razu i nie znosisz przygotowań.',
              earth: 'Działasz wolno i nie zatrzymujesz się w połowie.',
              air: 'Walczysz argumentem, nie siłą — i wygrywasz częściej.',
              water: 'Złość chowasz, aż wyjdzie okrężną drogą.' },
      Jupiter: { fire: 'Rośniesz przez ryzyko i nowe kierunki.',
                 earth: 'Rośniesz przez cierpliwe powiększanie tego, co już masz.',
                 air: 'Rośniesz przez ludzi, kontakty i wiedzę.',
                 water: 'Rośniesz przez sens i pomaganie, nie przez zysk.' },
      Saturn: { fire: 'Twoja lekcja to dokończyć to, co zacząłeś z entuzjazmem.',
                earth: 'Twoja lekcja to odpuścić kontrolę nad wynikiem.',
                air: 'Twoja lekcja to podjąć decyzję bez pełnych danych.',
                water: 'Twoja lekcja to nazwać własną granicę na głos.' },
      Uranus: { fire: 'Wolność potrzebujesz w działaniu — nikt nie ustawia Twojego tempa.',
                earth: 'Zmiana przychodzi u Ciebie rzadko, ale wtedy całkowicie.',
                air: 'Myślisz inaczej niż otoczenie i to jest Twój zasób.',
                water: 'Twoja niezależność jest emocjonalna: nie oddasz wnętrza.' },
      Neptune: { fire: 'Marzysz o wielkiej roli i łatwo idealizujesz własną misję.',
                 earth: 'Twoja wyobraźnia potrzebuje formy, inaczej się rozpuszcza.',
                 air: 'Idee porywają Cię mocniej niż ludzie.',
                 water: 'Granica między Tobą a innymi jest cienka od zawsze.' },
      Pluto: { fire: 'Władzę przejmujesz przez działanie, nie przez negocjację.',
               earth: 'Kontrolę utrzymujesz przez wytrwałość i zasoby.',
               air: 'Wpływ zdobywasz informacją i tym, co wiesz o ludziach.',
               water: 'Twoja siła jest w tym, co pozostaje niewypowiedziane.' },
      Node: { fire: 'Kierunek rozwoju: brać inicjatywę zamiast czekać na pozwolenie.',
              earth: 'Kierunek rozwoju: dokończyć i utrzymać, nie tylko zacząć.',
              air: 'Kierunek rozwoju: wyjść do ludzi i mówić wprost.',
              water: 'Kierunek rozwoju: wpuścić uczucia, nie tylko je analizować.' }
    },

    /* --- фазы Луны ------------------------------------------------------- */
    moonPhase: [
      { n: 'Nów', t: 'Początek cyklu. Dobra doba na zamiar i pierwszy krok, zła na podsumowania.' },
      { n: 'Sierp rosnący', t: 'Energia narasta. To moment, żeby zacząć realnie, a nie tylko planować.' },
      { n: 'Pierwsza kwadra', t: 'Pierwszy opór w cyklu. Zwykle tu okazuje się, czego zabrakło w planie.' },
      { n: 'Garbaty rosnący', t: 'Faza dopracowania. Dobrze idą poprawki, źle nowe otwarcia.' },
      { n: 'Pełnia', t: 'Maksimum napięcia i widoczności. Emocje mocniejsze niż sprawy, które je wywołały.' },
      { n: 'Garbaty malejący', t: 'Czas dzielenia się wynikiem. Dobry moment na rozmowy i wnioski.' },
      { n: 'Ostatnia kwadra', t: 'Faza odpuszczania. Dobrze idzie kończenie, źle rozpoczynanie.' },
      { n: 'Sierp malejący', t: 'Koniec cyklu. Odpoczynek daje więcej niż wysiłek.' }
    ],

    /* --- ретрограды ------------------------------------------------------ */
    retro: {
      Mercury: 'Merkury retrogradny: nieporozumienia, powracające tematy i sprzęt, który wybiera właśnie ten moment. Zamiast startować — domykaj.',
      Venus: 'Wenus retrogradna: wracają byli i pytanie, ile jest warta Twoja praca. Zły okres na duże zakupy dla wizerunku.',
      Mars: 'Mars retrogradny: energia idzie w środek zamiast na zewnątrz. Konflikty odkładane teraz wracają później mocniejsze.',
      Jupiter: 'Jowisz retrogradny: wzrost przenosi się do wewnątrz. Rewizja planów sprawdza się lepiej niż ekspansja.',
      Saturn: 'Saturn retrogradny: rachunek za odłożone obowiązki przychodzi w łagodniejszej formie, ale przychodzi.',
      Uranus: 'Uran retrogradny: potrzeba zmiany jest, ale wyraża się jako wewnętrzny niepokój, nie jako ruch.',
      Neptune: 'Neptun retrogradny: iluzje się rozwiewają. Bywa nieprzyjemnie i bywa bardzo potrzebne.',
      Pluto: 'Pluton retrogradny: temat władzy i kontroli wraca do przemyślenia, zamiast rozgrywać się na zewnątrz.'
    },

    /* --- числа ----------------------------------------------------------- */
    numbers: {
      1: 'Samodzielność, inicjatywa, trudność z proszeniem o pomoc.',
      2: 'Wrażliwość na ludzi, mediacja, ryzyko rozmycia własnych granic.',
      3: 'Ekspresja, słowo, kontakt. Ryzyko rozproszenia na dziesięć kierunków.',
      4: 'Struktura, praca, cierpliwość. Odpoczynek traktowany jak coś do zasłużenia.',
      5: 'Ruch, wolność, zmiana. Rutyna wypala szybciej niż przeciążenie.',
      6: 'Odpowiedzialność za innych, dom, opieka. Trudność z odmawianiem.',
      7: 'Analiza, samotność, potrzeba sensu. Dystans bywa czytany jako chłód.',
      8: 'Władza, pieniądze, skala. Cena to trudność z pokazaniem słabości.',
      9: 'Szerokie spojrzenie, pomaganie, zamykanie cykli. Trudność z odpuszczaniem.',
      11: 'Liczba mistrzowska: wysoka wrażliwość i intuicja przy nierównym poczuciu bezpieczeństwa.',
      22: 'Liczba mistrzowska: zdolność budowania w dużej skali, wymagająca wieloletniej cierpliwości.',
      33: 'Liczba mistrzowska: nauczanie i opieka jako oś życia, z ryzykiem oddawania wszystkiego.'
    },
    numCategory: {
      lifePath: 'Główna oś życia, wyliczona z pełnej daty urodzenia.',
      expression: 'Jak działasz na zewnątrz — z pełnego imienia i nazwiska.',
      soul: 'Czego naprawdę chcesz — z samogłosek imienia.',
      personality: 'Co widzą inni na pierwszym kontakcie — ze spółgłosek.',
      birthday: 'Wrodzony talent, wyliczony z dnia miesiąca.',
      maturity: 'Kierunek drugiej połowy życia: droga życia plus liczba wyrazu.',
      personalYear: 'Temat bieżącego cyklu rocznego. Zmienia się w dniu urodzenia, nie 1 stycznia.',
      personalMonth: 'Temat bieżącego miesiąca w ramach roku osobistego.',
      personalDay: 'Temat dnia. Najkrótszy i najsłabszy z cykli.'
    },
    karmicText: {
      13: 'Dług 13: wynik wymaga pracy bez skrótów.',
      14: 'Dług 14: nauka umiaru i wolności bez ucieczki.',
      16: 'Dług 16: stare wyobrażenie o sobie musi się rozpaść.',
      19: 'Dług 19: samodzielność bez odcinania się od ludzi.'
    }
  };

  var EN = {
    ui: {
      brand: 'AstroMap',
      nav: { today: 'Today', horoscope: 'Horoscope', chart: 'Chart',
             match: 'Compatibility', numbers: 'Numerology', moon: 'Moon',
             retro: 'Retrogrades', profile: 'Profile' },
      todayTitle: 'Today', horoscopeTitle: 'Horoscope', chartTitle: 'Your chart',
      matchTitle: 'Compatibility', numbersTitle: 'Numerology',
      moonTitle: 'Moon calendar', retroTitle: 'Retrogrades',
      profileTitle: 'Profile',
      needTitle: 'Birth details first',
      needText: 'This screen is calculated from your date, time and place of birth. Fill them in once — every other screen then works on its own.',
      needBtn: 'Go to profile',
      needTextNum: 'Numerology is calculated from your birth date and name. Fill in the profile to see your numbers.',
      needTextMatch: 'Compatibility needs two charts. Add your own details in the profile first, then add the second person here.',
      skyNow: 'Sky right now',
      skyNote: 'Current planetary positions. This card doesn\u2019t depend on your data — it is the same for everyone.',
      whatYouGet: 'What we calculate',
      numbersRef: 'What the numbers mean',
      matchIntro: 'How to read compatibility',
      matchIntroText: 'The index comes from aspects between the two charts, with Sun, Moon, Venus and Mars contacts weighted heaviest. The composite is a third chart built from midpoints — it shows the relationship as its own entity.',
      profileIntro: 'The birth time changes the Ascendant and the houses. If you don\u2019t know it, leave the field empty — everything else still works.',
      getList: [
        'Indices of the day and active transits',
        'Exact transit dates for a day, a week and a month',
        'Chart: planets, aspects, elemental balance',
        'Compatibility with another person and the composite chart',
        'Numerology: numbers and personal cycles',
        'Moon calendar and retrogrades'
      ],
      indices: 'Indices of the day',
      indicesNote: 'Computed from the tone of active transits to the relevant points of your chart. An index, not a prediction.',
      mood: 'Mood', work: 'Work', love: 'Love',
      activeTransits: 'Active transits',
      exactDates: 'Exact dates',
      noTransits: 'No aspects within orb for this date.',
      period: { today: 'Today', tomorrow: 'Tomorrow', week: 'Weekly', month: 'Monthly',
                halfyear: 'Half-year', year: 'Yearly' },
      hzGeneral: 'General Overview', hzLove: 'Love & Relationships', hzCareer: 'Career & Work', hzLuck: 'Luck & Fortune',
      hzQuiet: 'A quiet stretch — no strong aspects in this area right now.',
      day: 'Day', week: 'Week', month: 'Month', dateCol: 'Date',
      transitCol: 'Transit', weight: 'Pair weight',
      positions: 'Positions', aspects: 'Aspects', balance: 'Balance',
      elements: 'Elements', modes: 'Modes',
      houses: 'Houses (whole sign)',
      point: 'Point', sign: 'Sign', deg: 'Degree', house: 'House',
      motion: 'Motion', retroCol: 'R', orb: 'Orb', tone: 'Tone',
      partnerTitle: 'Second person', partnerAdd: 'Calculate compatibility',
      partnerName: 'Name', date: 'Date of birth', time: 'Time',
      city: 'Place', noTime: 'I don\u2019t know the time',
      index: 'Compatibility index',
      indexNote: 'A 38–96 scale built from the twelve strongest contacts between the charts. Astrological method, not a prediction.',
      strongest: 'Strongest contacts',
      composite: 'Composite chart',
      compositeNote: 'A midpoint chart: it shows the relationship as its own entity, not the sum of two people.',
      lifePath: 'Life path', expression: 'Expression number',
      soul: 'Soul urge', personalityN: 'Personality number',
      birthdayN: 'Birthday number', maturity: 'Maturity number',
      pYear: 'Personal year', pMonth: 'Personal month', pDay: 'Personal day',
      karmic: 'Karmic debt', master: 'Master number',
      nameNeeded: 'Add your name in the profile to calculate the name numbers.',
      phase: 'Phase', illum: 'Illumination', moonSign: 'Moon in sign',
      nextFull: 'Next full moon', nextNew: 'Next new moon',
      stationing: 'Station', direct: 'direct',
      retrograde: 'retrograde', noRetro: 'No planet is retrograde right now.',
      save: 'Save', edit: 'Edit', calc: 'Calculate',
      disclaimer: 'This content is for entertainment and does not replace professional advice.',
      noProfile: 'Fill in your birth details to calculate the chart.',
      timeMissing: 'Without a birth time we don\u2019t calculate the Ascendant, MC or houses.'
    },

    signs: ['Aries', 'Taurus', 'Gemini', 'Cancer', 'Leo', 'Virgo',
            'Libra', 'Scorpio', 'Sagittarius', 'Capricorn', 'Aquarius', 'Pisces'],
    elements: { fire: 'Fire', earth: 'Earth', air: 'Air', water: 'Water' },
    modes: { cardinal: 'Cardinal', fixed: 'Fixed', mutable: 'Mutable' },
    planets: {
      Sun: 'Sun', Moon: 'Moon', Mercury: 'Mercury', Venus: 'Venus',
      Mars: 'Mars', Jupiter: 'Jupiter', Saturn: 'Saturn', Uranus: 'Uranus',
      Neptune: 'Neptune', Pluto: 'Pluto', Node: 'Lunar Node',
      ASC: 'Ascendant', MC: 'MC'
    },
    aspects: {
      conjunction: 'conjunction', sextile: 'sextile', square: 'square',
      trine: 'trine', opposition: 'opposition'
    },

    tone: { soft: 'supports', hard: 'strains', neutral: 'intensifies' },
    toneWord: { soft: 'easy', hard: 'hard', neutral: 'neutral' },

    tPlanet: {
      Sun: { subj: 'The transiting Sun', theme: 'visibility and where your attention goes',
             advice: 'It lasts a day or two — don\u2019t build anything long on it.' },
      Moon: { subj: 'The transiting Moon', theme: 'mood and the need for closeness',
              advice: 'A few hours. If the reaction is bigger than the cause, this is why.' },
      Mercury: { subj: 'Transiting Mercury', theme: 'conversations, paperwork and thinking speed',
                 advice: 'A good moment to send the thing that has been sitting for a week.' },
      Venus: { subj: 'Transiting Venus', theme: 'relationships, money and self-worth',
               advice: 'A short window where reconciliation and asking for a raise both land better.' },
      Mars: { subj: 'Transiting Mars', theme: 'energy, anger and readiness to act',
              advice: 'Put it into movement or work, otherwise it goes into an argument.' },
      Jupiter: { subj: 'Transiting Jupiter', theme: 'expansion and an opening that only needs a decision',
                 advice: 'It runs for weeks. The main risk is overestimating your capacity.' },
      Saturn: { subj: 'Transiting Saturn', theme: 'structure, limits and the cost of time',
                advice: 'It runs for months. Not a punishment, a bill — pay it in small instalments.' },
      Uranus: { subj: 'Transiting Uranus', theme: 'the change you did not plan',
                advice: 'You cannot wait it out. You can choose which part you change yourself.' },
      Neptune: { subj: 'Transiting Neptune', theme: 'blurred boundaries and idealisation',
                 advice: 'A poor period for decisions that need sharp sight. A good one for making things.' },
      Pluto: { subj: 'Transiting Pluto', theme: 'what is ending anyway',
               advice: 'It works over years. Resistance costs more than the change.' },
      Node: { subj: 'The transiting Lunar Node', theme: 'the direction that pulls despite comfort',
              advice: 'The turning point often only becomes visible six months later.' }
    },

    nPoint: {
      Sun: 'your sense of self',
      Moon: 'your need for safety',
      Mercury: 'the way you speak and think',
      Venus: 'your relationships and what you treat as valuable',
      Mars: 'your capacity to act and confront',
      Jupiter: 'your sense of meaning and scale',
      Saturn: 'your limits and obligations',
      Uranus: 'your need for freedom',
      Neptune: 'your sensitivity and imagination',
      Pluto: 'your relationship with power and control',
      Node: 'your direction of growth',
      ASC: 'the way you enter situations',
      MC: 'your professional standing and how you are seen'
    },

    planetElement: {
      Sun: { fire: 'Your identity works through movement and initiative.',
             earth: 'Your identity is built by results, not announcements.',
             air: 'Your identity exists in contact with people and ideas.',
             water: 'Your identity rests on what you feel, not what you do.' },
      Moon: { fire: 'Your emotions are fast and visible: it bursts, then it\u2019s over.',
              earth: 'The concrete calms you: rhythm, food, a familiar place.',
              air: 'You need to name a feeling in words before you can have it.',
              water: 'You feel more than you say, and longer than is convenient.' },
      Mercury: { fire: 'You speak faster than you verify. An asset at the start, a risk in detail.',
                 earth: 'You think concretely and can\u2019t stand abstraction without an example.',
                 air: 'Curiosity is your main intellectual fuel.',
                 water: 'You understand through association and mood, not through tables.' },
      Venus: { fire: 'In love you need pace and to be chosen out loud.',
               earth: 'In love you count repetition, not declarations.',
               air: 'In love the conversation matters more than the gesture.',
               water: 'In love you merge with the other person faster than is safe.' },
      Mars: { fire: 'You act immediately and hate preparation.',
              earth: 'You act slowly and never stop halfway.',
              air: 'You fight with argument, not force — and win more often.',
              water: 'You hide anger until it comes out sideways.' },
      Jupiter: { fire: 'You grow through risk and new directions.',
                 earth: 'You grow by patiently enlarging what you already have.',
                 air: 'You grow through people, contacts and knowledge.',
                 water: 'You grow through meaning and helping, not profit.' },
      Saturn: { fire: 'Your lesson is finishing what enthusiasm started.',
                earth: 'Your lesson is letting go of control over the outcome.',
                air: 'Your lesson is deciding without the full data.',
                water: 'Your lesson is naming your own limit out loud.' },
      Uranus: { fire: 'You need freedom in action — nobody sets your tempo.',
                earth: 'Change comes rarely for you, and then completely.',
                air: 'You think unlike your surroundings, and that is the asset.',
                water: 'Your independence is emotional: you won\u2019t hand over the inside.' },
      Neptune: { fire: 'You dream of a large role and idealise your own mission.',
                 earth: 'Your imagination needs form, otherwise it dissolves.',
                 air: 'Ideas carry you away more than people do.',
                 water: 'The border between you and others has always been thin.' },
      Pluto: { fire: 'You take power by acting, not negotiating.',
               earth: 'You hold control through endurance and resources.',
               air: 'You gain influence through information and what you know about people.',
               water: 'Your strength is in what stays unsaid.' },
      Node: { fire: 'Direction of growth: take initiative instead of waiting for permission.',
              earth: 'Direction of growth: finish and hold, not only begin.',
              air: 'Direction of growth: go out to people and say it plainly.',
              water: 'Direction of growth: let feelings in, not only analyse them.' }
    },

    moonPhase: [
      { n: 'New moon', t: 'Start of the cycle. A good day for an intention and a first step, a bad one for summaries.' },
      { n: 'Waxing crescent', t: 'Energy rises. This is the moment to actually begin, not just plan.' },
      { n: 'First quarter', t: 'The first resistance of the cycle. Usually where the gap in the plan shows up.' },
      { n: 'Waxing gibbous', t: 'The refining phase. Corrections go well, new openings don\u2019t.' },
      { n: 'Full moon', t: 'Peak tension and visibility. Feelings run bigger than the things causing them.' },
      { n: 'Waning gibbous', t: 'Time to share the result. Good for conversations and conclusions.' },
      { n: 'Last quarter', t: 'The letting-go phase. Finishing goes well, starting does not.' },
      { n: 'Waning crescent', t: 'End of the cycle. Rest gives more than effort.' }
    ],

    retro: {
      Mercury: 'Mercury retrograde: misunderstandings, returning topics and hardware that picks exactly this moment. Close things instead of launching them.',
      Venus: 'Venus retrograde: exes return, and so does the question of what your work is worth. A poor time for big image purchases.',
      Mars: 'Mars retrograde: energy turns inward instead of out. Conflicts postponed now come back stronger later.',
      Jupiter: 'Jupiter retrograde: growth moves inward. Revising plans works better than expanding them.',
      Saturn: 'Saturn retrograde: the bill for postponed obligations arrives in a softer form, but it arrives.',
      Uranus: 'Uranus retrograde: the need for change is there, but shows up as inner restlessness rather than movement.',
      Neptune: 'Neptune retrograde: illusions dissolve. Unpleasant, and often necessary.',
      Pluto: 'Pluto retrograde: the theme of power and control returns for rethinking instead of playing out externally.'
    },

    numbers: {
      1: 'Independence, initiative, difficulty asking for help.',
      2: 'Sensitivity to people, mediation, the risk of blurred boundaries.',
      3: 'Expression, words, contact. The risk of scattering across ten directions.',
      4: 'Structure, work, patience. Rest treated as something to be earned.',
      5: 'Movement, freedom, change. Routine burns you out faster than overload.',
      6: 'Responsibility for others, home, care. Difficulty saying no.',
      7: 'Analysis, solitude, a need for meaning. Distance often reads as coldness.',
      8: 'Power, money, scale. The price is difficulty showing weakness.',
      9: 'Wide view, helping, closing cycles. Difficulty letting go.',
      11: 'Master number: high sensitivity and intuition alongside uneven security.',
      22: 'Master number: the capacity to build at scale, requiring years of patience.',
      33: 'Master number: teaching and care as the axis of life, with the risk of giving everything.'
    },
    numCategory: {
      lifePath: 'The main axis of the life, from the full birth date.',
      expression: 'How you operate outwardly — from the full name.',
      soul: 'What you actually want — from the vowels of the name.',
      personality: 'What others see on first contact — from the consonants.',
      birthday: 'An innate talent, from the day of the month.',
      maturity: 'The direction of the second half of life: life path plus expression.',
      personalYear: 'The theme of the current yearly cycle. It changes on your birthday, not on 1 January.',
      personalMonth: 'The theme of the current month within the personal year.',
      personalDay: 'The theme of the day. The shortest and weakest of the cycles.'
    },
    karmicText: {
      13: 'Debt 13: results demand work without shortcuts.',
      14: 'Debt 14: learning moderation and freedom without escape.',
      16: 'Debt 16: an old self-image has to fall apart.',
      19: 'Debt 19: independence without cutting people off.'
    }
  };

  g.T_ALL = { pl: PL, en: EN };
  /* Дефолт — английский; польский включается явно. */
  g.T = (g.APP_LANG === 'pl') ? PL : EN;
})(typeof window !== 'undefined' ? window : globalThis);
